---
title: "Final Projects"
description: "A list of final projects for PSYC 2040"
author: "Abhilasha Kumar"
date-modified: last-modified
order: 15
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page describes the details for your final project. Your final project is worth 10% of your final grade. You have the option to choose from six different options (see below). There will be several formative low-stakes milestones during the semester to ensure you are making steady progress towards the final project. 


## Milestones 

The breakdown of how the milestones contribute to your final project grade is below:

| Milestone | Points       |
|:-------------|:------------|
| Project selection            | 0.5    |
| Selection of instance of cognition           | 0.5  |
| QALMRI for research articles           | 2 |
| Project plan/outline            | 0.5 |
| First draft           | 0.5    |
| Final submission           | 6 |
| **Total**           | 10 |

### Milestone 1: Project selection (0.5 points)

This assessment will happen relatively early in the semester to ensure that you are clear on the different demands of the project options and are able to form a team (if required). This assessment will be graded for satisfactory effort, i.e., I want to see that you have made an effort to select the option that best aligns with your goals for this class. 

### Milestone 2: Selection of instance of cognition (0.5 points)

This assessment will help you think about the particular instance of cognition that you might want to explore. Note that the instance of cognition you select will depend on the project you have selected, so this assessment may also involve describing some specifics of your project (see details below). This assessment will be graded for satisfactory effort, i.e., I want to see that you have made an effort to identify an instance of cognition that aligns well with the project you have selected. 

### Milestone 3: QALMRI for research articles (2 points)

This assessment will help you organize your literature review and structure your analysis and/or writing. You will select 3 primary research articles relevant to your project and submit QALMRI reports for each of the articles. This will help you understand the research articles in detail and enable you to ultimately connect ideas across readings.

### Milestone 4: Project plan/outline (0.5 points)

This assessment is intended to help you organize your overall plan for the final project. The specifics of the plan/outline will vary based on your chosen project, but you will be required to submit a rough outline/plan. This assessment will be graded for satisfactory effort, i.e., I want to see that you are making steady progress on your project and are able to integrate the research articles you have read with key arguments/analyses. 

### Milestone 5: First draft (0.5 points)

This assessment is intended to provide you feedback on your nearly-final submission. The goal is to make sure you are on track to submitting a strong final project.This assessment will be graded for satisfactory effort, i.e., I want to see that you are making steady progress on your project.

### Milestone 6: Final submission (6 points)

This final assessment will require you to submit your final project and all its components. The specifics of your submission will vary based on your chosen project, so please refer to the details of your project below to make sure you submit all required materials.

## Project options

You can either choose to do a group project or an individual project. All projects are worth 10% of your grade. 

### Group projects

#### Minute Cognition

For this project, you will create a 3 to 5 minute video on any instance of cognition that we have discussed as part of this class or did not cover but interests you. Your video should introduce the topic, examine its relevance to real life, and then describe the research that has been conducted on the topic so far in an engaging and educational manner. Details about different milestones for this project are available [here](https://docs.google.com/document/d/1WiAL1RBFt6OLRx-43awGxZacst2UJXYZ/edit?usp=share_link&ouid=114230382498081849934&rtpof=true&sd=true).

#### Gamifying Cognition

For this project, you will create a game that tests an instance of cognition. The game can be single or multi-player, but you will need to specify (1) your target research question, (2) independent variable(s), (3) dependent variables, and (4) expected patterns of behavior and how they correspond to the instance of cognition you are attempting to study. The game should be playable in person (via index cards, etc.) or online (via a survey). Details about different milestones for this project are available [here](https://docs.google.com/document/d/1rC8gnxmMbp9vuKWeEDv0rLzBRRlTAqnd/edit?usp=sharing&ouid=114230382498081849934&rtpof=true&sd=true).

#### Cognition in Film

For this project, you will explore a cognitive phenomenon in the realistic or fictionalized world of a film. Through a jointly written short paper, you will make connections between a cognitive phenomenon demonstrated in a film and research findings or frameworks discussed in class. Details about different milestones for this project are available [here](https://docs.google.com/document/d/1y-cnQp_5vudgVisZNZHmiqiuqZDs7OZ5/edit?usp=sharing&ouid=114230382498081849934&rtpof=true&sd=true).



### Individual Projects

#### Analyze AI

For this project, you will select and analyze any real-world example of AI from a cognitive lens. For example, you could select chatGPT and analyze how well it mimics human language. You will come up with a clear question you hope to answer, your plan for answering this question, and then present your findings through a 5-7 page paper. Details about different milestones for this project are available [here](https://docs.google.com/document/d/1hpwrcv_-oFMDxW65jqwiLUNfdrnAUJrF/edit?usp=sharing&ouid=114230382498081849934&rtpof=true&sd=true).

#### Podcast Pondering

For this project, you will select a podcast from the [Many Minds archive](https://manyminds.libsyn.com/) and analyze the discussion in the podcast from a *cognitive* perspective. You will be required to connect ideas from the class to the concepts discussed in the podcast, and then submit a short 5-7 page paper. Details about different milestones for this project are available [here](https://docs.google.com/document/d/1DsKxioZ_rG57afXAN0zEfWv3pTSomIQd/edit?usp=sharing&ouid=114230382498081849934&rtpof=true&sd=true).


#### Data Dive

For this project, you will analyze the main patterns from a dataset provided by me. Your goal is to explore the dataset using different types of analyses, visualize the main patterns via some type of graph/plot, and communicate your analysis via a short report. You are welcome to use any software (Excel, R, SPSS, etc.) to conduct your analyses. Details about different milestones for this project are available [here](https://docs.google.com/document/d/1Oq7J6iDjDic26lEbaUu48CMwUWHrf5Ob/edit?usp=sharing&ouid=114230382498081849934&rtpof=true&sd=true).


