---
title: "Additional resources"
description: "Additional resources for PSYC 2040"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Interesting perspectives/research/videos

Carol Dweck on [The power of believing that you can improve](https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve?language=en)

## Helpful library resources

[Course Reserves Search](https://cbbcat.net/screens/reserves.html): Search for course reserves by your professor's name or course ID.

[Need Research Help? Ask a Librarian!](https://library.bowdoin.edu/research/appointment.shtml): Meet with a research librarian in-person or virtually.

[Research Guides by Subject](https://bowdoin.libguides.com/): Find research resources by subject or course curated by Bowdoin librarians.

[Library Databases](https://bowdoin.libguides.com/az.php): Access articles, streaming music & video, primary sources, images, and more from over 500 databases.

[Style and Citation Guides](https://library.bowdoin.edu/research/citation-guides.shtml): Citation style guides, when and how to cite, and citation management tools.

## List of Cognitive Science Journals

Primary research articles and review aricles about cognition and intelligence are published in many journals. Here is a short list of journals where you might find review articles and empirical articles. Please note that this list is not exhaustive but simply a representative sample of journals we might encounter in class and you might consider looking through for your final projects.

### Journals for Review Articles (SPARKs)

- [Psychological Bulletin](https://www.apa.org/pubs/journals/bul)
- [Psychological Review](https://www.apa.org/pubs/journals/rev)
-   [Annual Reviews of Psychology](https://www.annualreviews.org/journal/psych)
- [Psychonomic Bulletin & Review](https://www.psychonomic.org/page/pbr)
-   [Current Directions in Psychological Science](https://www.psychologicalscience.org/publications/current_directions)
-   [Psychological Science in the Public Interest](https://www.psychologicalscience.org/publications/pspi)
-   [Perspectives on Psychological Science](https://www.psychologicalscience.org/publications/perspectives)
-   [Trends in Cognitive Sciences](https://www.cell.com/trends/cognitive-sciences/home)
- [Trends in Neurosciences](https://www.cell.com/trends/neurosciences/home)
- [Nature Reviews Psychology](https://www.nature.com/nrpsychol/)
- [WIREs Cognitive Science](https://wires.onlinelibrary.wiley.com/journal/19395086)
- [The Philosophical Review](https://read.dukeupress.edu/the-philosophical-review)
- Philosophical Transactions of the Royal Society [A](https://royalsocietypublishing.org/journal/rsta) and [B](https://royalsocietypublishing.org/journal/rstb)

### Journals for Primary Research Articles

-   [Psychonomic Bulletin & Review](https://www.psychonomic.org/page/pbr)
-   [Memory & Cognition](https://www.psychonomic.org/page/mc)
-   [Attention, Perception & Psychophysics](https://www.psychonomic.org/page/app)
-   [Learning & Behavior](https://www.psychonomic.org/page/lb)
-   [Behavior Research Methods](https://www.psychonomic.org/page/brm)
-   [Cognitive Research: Principles & Implications](https://www.psychonomic.org/page/crpi)
-   [Journals of Experimental Psychology: General](https://www.apa.org/pubs/journals/xge)
-   [Journals of Experimental Psychology: Animal Learning and Cognition](https://www.apa.org/pubs/journals/xan)
-   [Journals of Experimental Psychology: Human, Perception, and Performance](https://www.apa.org/pubs/journals/xhp)
-   [Journals of Experimental Psychology: Learning, Memory, and Cognition](https://www.apa.org/pubs/journals/xlm)
-   [Canadian Journal of Experimental Psychology](https://www.apa.org/pubs/journals/cep)
-   [Psychological Review](https://www.apa.org/pubs/journals/rev)
-   [Psychological Science](https://www.psychologicalscience.org/publications/psychological_science)
-   [Current Directions in Psychological Science](https://www.psychologicalscience.org/publications/current_directions)
-   [Psychological Science in the Public Interest](https://www.psychologicalscience.org/publications/pspi)
-   [Perspectives on Psychological Science](https://www.psychologicalscience.org/publications/perspectives)
-   [Cognitive Psychology](https://www.journals.elsevier.com/cognitive-psychology)
-   [Journal of Memory and Language](https://www.journals.elsevier.com/journal-of-memory-and-language)
-   [Cognition](https://www.journals.elsevier.com/cognition)
-   [Cognitive Science](https://cognitivesciencesociety.org/cognitive-science-journal/)
-   [The Journal of Cognition](https://www.journalofcognition.org)
-   [Memory](https://www.tandfonline.com/toc/pmem20/current)
-   [Nature Human Behavior](https://www.nature.com/nathumbehav/)
-   [The Quarterly Journal of Experimental Psychology](https://journals.sagepub.com/home/qjp)
-   [Consciousness and Cognition](https://www.journals.elsevier.com/consciousness-and-cognition)
-   [Acta Psychologica](https://www.journals.elsevier.com/acta-psychologica)
-   [Behavioral and Brain Sciences](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences)
